/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./App.tsx", "./index.tsx"],
  safelist: [
    "bg-brand-500/10",
    "bg-brand-500/20",
    "bg-blue-500/10",
    "bg-blue-500/20",
    "bg-purple-500/10",
    "bg-purple-500/20",
    "bg-green-500/10",
    "bg-green-500/20",
    "text-brand-400",
    "text-blue-400",
    "text-purple-400",
    "text-green-400",
    "border-brand-500",
    "border-brand-500/20",
    "border-blue-500",
    "border-blue-500/20",
    "border-purple-500",
    "border-purple-500/20",
    "from-brand-500",
    "from-blue-500",
    "from-purple-500",
    "to-brand-400",
    "to-blue-400",
    "to-purple-400",
    "bg-brand-600",
    "bg-blue-600",
    "bg-purple-600",
    "hover:bg-brand-500",
    "hover:bg-blue-500",
    "hover:bg-purple-500",
    "shadow-brand-500/20",
    "shadow-blue-500/20",
    "shadow-purple-500/20",
    "group-hover:bg-brand-500/20",
    "group-hover:bg-purple-500/20",
    "group-hover:bg-green-500/20",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      colors: {
        brand: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
          950: "#082f49",
        },
        dark: {
          bg: "#0f172a",
          card: "#1e293b",
          surface: "#334155",
        },
      },
      animation: {
        breathe: "breathe 8s infinite ease-in-out",
        float: "float 6s ease-in-out infinite",
        box: "box 8s infinite linear",
        coherent: "coherent 6s infinite ease-in-out",
        cyclic: "cyclic 6s infinite ease-out",
        "text-breathe-inhale": "text-breathe-inhale 8s infinite ease-in-out",
        "text-breathe-exhale": "text-breathe-exhale 8s infinite ease-in-out",
        "text-box-inhale": "text-box-inhale 8s infinite linear",
        "text-box-hold1": "text-box-hold1 8s infinite linear",
        "text-box-exhale": "text-box-exhale 8s infinite linear",
        "text-box-hold2": "text-box-hold2 8s infinite linear",
        "text-coherent-inhale": "text-coherent-inhale 6s infinite ease-in-out",
        "text-coherent-exhale": "text-coherent-exhale 6s infinite ease-in-out",
        "text-cyclic-inhale": "text-cyclic-inhale 6s infinite ease-out",
        "text-cyclic-exhale": "text-cyclic-exhale 6s infinite ease-out",
      },
      keyframes: {
        breathe: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.8" },
          "50%": { transform: "scale(1.5)", opacity: "0.4" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        box: {
          "0%": { transform: "scale(1)" },
          "25%": { transform: "scale(1.5)" },
          "50%": { transform: "scale(1.5)" },
          "75%": { transform: "scale(1)" },
          "100%": { transform: "scale(1)" },
        },
        coherent: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.85" },
          "50%": { transform: "scale(1.5)", opacity: "0.5" },
        },
        cyclic: {
          "0%": { transform: "scale(1)" },
          "40%": { transform: "scale(1.3)" },
          "55%": { transform: "scale(1.5)" },
          "100%": { transform: "scale(1)" },
        },
        "text-breathe-inhale": {
          "0%, 49.9%": { opacity: "1" },
          "50%, 100%": { opacity: "0" },
        },
        "text-breathe-exhale": {
          "0%, 49.9%": { opacity: "0" },
          "50%, 100%": { opacity: "1" },
        },
        "text-box-inhale": {
          "0%, 24.9%": { opacity: "1" },
          "25%, 100%": { opacity: "0" },
        },
        "text-box-hold1": {
          "0%, 24.9%": { opacity: "0" },
          "25%, 49.9%": { opacity: "1" },
          "50%, 100%": { opacity: "0" },
        },
        "text-box-exhale": {
          "0%, 49.9%": { opacity: "0" },
          "50%, 74.9%": { opacity: "1" },
          "75%, 100%": { opacity: "0" },
        },
        "text-box-hold2": {
          "0%, 74.9%": { opacity: "0" },
          "75%, 100%": { opacity: "1" },
        },
        "text-coherent-inhale": {
          "0%, 49.9%": { opacity: "1" },
          "50%, 100%": { opacity: "0" },
        },
        "text-coherent-exhale": {
          "0%, 49.9%": { opacity: "0" },
          "50%, 100%": { opacity: "1" },
        },
        "text-cyclic-inhale": {
          "0%, 54.9%": { opacity: "1" },
          "55%, 100%": { opacity: "0" },
        },
        "text-cyclic-exhale": {
          "0%, 54.9%": { opacity: "0" },
          "55%, 100%": { opacity: "1" },
        },
      },
    },
  },
};
